# Normal Equation

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import time
from sklearn.datasets import load_boston

In [2]:
boston_dataset = load_boston()

/home/gabry/Dataspell/LinearRegression/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Cal

In [3]:
boston_df = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
boston_df['MEDV'] = boston_dataset.target

## Normal Equation definition

$$\large \theta = (X^T X)^{-1}X^Ty$$

In [34]:
def normalEquation(X,y):
    etime = -time.time()
    theta = np.linalg.pinv(X.T.dot(X)).dot(X.T).dot(y)
    etime += time.time()
    etime = np.round(etime*1000,3)
    return theta, etime

### Inverse and Pseudo Inverse Matrix

In [30]:
A = np.array([[1,2,3],[2,4,6],[0,5,7]])
B = np.array([[17,13,3],[2,4,6],[0,5,7]])
np.linalg.det(A)

0.0

In [27]:
np.linalg.inv(A)

LinAlgError: Singular matrix

In [28]:
np.linalg.pinv(A)

array([[ 0.19733333,  0.39466667, -0.41333333],
       [-0.01866667, -0.03733333,  0.10666667],
       [ 0.01333333,  0.02666667,  0.06666667]])

In [31]:
np.linalg.det(B)

-186.00000000000009

In [32]:
np.linalg.inv(B)

array([[ 0.01075269,  0.40860215, -0.35483871],
       [ 0.07526882, -0.63978495,  0.51612903],
       [-0.05376344,  0.45698925, -0.22580645]])

In [33]:
np.linalg.pinv(B)

array([[ 0.01075269,  0.40860215, -0.35483871],
       [ 0.07526882, -0.63978495,  0.51612903],
       [-0.05376344,  0.45698925, -0.22580645]])

## Fitting models

In [36]:
selected_feature = 'RM'
X = boston_df[[selected_feature]].values
y = boston_df[["MEDV"]].values

In [37]:
X_linear = np.c_[np.ones((X.shape[0],1)), X]

In [38]:
theta,etime = normalEquation(X_linear,y)

theta value found by normal equation differs from the values found with gradient descend

In [39]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(X_linear,y)
reg.coef_

array([[0.        , 9.10210898]])

In [40]:
reg.intercept_

array([-34.67062078])

this confirm that normal equation give us the correct result, so changing learning rate to 0.01 in gradient descent we get improvement in the value of theta